title: Marco Tompitak
description: My GitHub Page
author: Marco Tompitak
logo: /static/img/avatar.svg
github: https://github.com/marcotompitak
about: Biophysicist

baseurl: ""
url: ""

allowsearch: false 

disqus_shortname: none
google_analytics: UA-47199852-2

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
